#!/usr/bin/env python3
"""Collect the studio's upstream contributions from the GitHub search API and write
data/contributions.toml, which templates/partials/contributions.html renders.

    python3 design/contributions.py            # inside `nix develop`
    GITHUB_TOKEN=... python3 design/contributions.py   # 30 instead of 10 searches per minute

Pull requests authored by the GitHub user are aggregated per repository; repositories under the
studio's own accounts are left out. Entries under [[manual]] in the existing file are kept as they
are: they record contributions on other forges (Kitware GitLab, gitlab.com, Bitbucket) that the
GitHub API cannot see. Output order is deterministic so the diff stays readable.
"""
import datetime, json, os, pathlib, re, sys, time, urllib.parse, urllib.request

USER = "FlorianFranzen"
OWN = {"florianfranzen", "gliology", "neurosuite"}
TOP = 14                  # repositories shown on the site
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "data/contributions.toml"
TOKEN = os.environ.get("GITHUB_TOKEN")
PAUSE = 2.5 if TOKEN else 7.0   # seconds between search calls (10/min unauthenticated)

def get(url):
    req = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json", "User-Agent": "fred.build-contributions"})
    if TOKEN:
        req.add_header("Authorization", f"Bearer {TOKEN}")
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)

def search(q):
    items, page = [], 1
    while True:
        url = f"https://api.github.com/search/issues?q={urllib.parse.quote(q)}&per_page=100&page={page}"
        data = get(url)
        items += data["items"]
        if len(items) >= data["total_count"] or not data["items"]:
            return items
        page += 1
        time.sleep(PAUSE)

print("searching pull requests…", file=sys.stderr)
prs = search(f"author:{USER} type:pr")
time.sleep(PAUSE)
print("counting issues…", file=sys.stderr)
issues = get(f"https://api.github.com/search/issues?q={urllib.parse.quote(f'author:{USER} type:issue')}&per_page=1")["total_count"]

repos = {}
for pr in prs:
    full = pr["repository_url"].split("/repos/")[1]
    owner = full.split("/")[0]
    if owner.lower() in OWN:
        continue
    r = repos.setdefault(full, {"prs": 0, "merged": 0, "first": pr["created_at"][:10], "last": pr["created_at"][:10]})
    r["prs"] += 1
    if pr["pull_request"].get("merged_at"):
        r["merged"] += 1
    r["first"] = min(r["first"], pr["created_at"][:10])
    r["last"] = max(r["last"], pr["created_at"][:10])

counted = [pr for pr in prs if pr["repository_url"].split("/repos/")[1].split("/")[0].lower() not in OWN]
totals = {
    "prs": len(counted),
    "merged": sum(1 for pr in counted if pr["pull_request"].get("merged_at")),
    "open": sum(1 for pr in counted if pr["state"] == "open"),
    "repositories": len(repos),
    "owners": len({f.split("/")[0] for f in repos}),
    "first_year": min(r["first"] for r in repos.values())[:4],
    "last_year": max(r["last"] for r in repos.values())[:4],
    "issues": issues,
}

# rank: merged PRs first, then stars; fetch metadata for the candidates only
ranked = sorted(repos.items(), key=lambda kv: (-kv[1]["merged"], -kv[1]["prs"], kv[0]))
shown = []
for full, r in ranked[: TOP + 6]:
    if r["merged"] == 0:
        continue
    meta = get(f"https://api.github.com/repos/{full}")
    desc = re.sub(r":[a-z0-9_+-]+:", "", meta.get("description") or "").strip()   # drop GitHub emoji shortcodes
    shown.append({
        "name": full, "url": meta["html_url"], "description": desc,
        "language": meta.get("language") or "", "stars": meta.get("stargazers_count", 0),
        "archived": meta.get("archived", False), **r,
    })
    time.sleep(0.5)
shown.sort(key=lambda r: (-r["merged"], -r["stars"], r["name"]))
shown = shown[:TOP]

# keep the hand-maintained entries and the intro from the previous file
manual, intro = [], ""
if OUT.exists():
    text = OUT.read_text()
    # the first [[manual]] table header (the file's own header comment mentions the name too),
    # together with the comment lines directly above it
    m = re.search(r"^(?:#.*\n)*\[\[manual\]\]$", text, flags=re.M)
    if m:
        manual_text = text[m.start():]
        manual_text = manual_text.split("\n[[repo]]")[0] if "\n[[repo]]" in manual_text else manual_text
        manual = [manual_text]
    for line in text.splitlines():
        if line.startswith("intro = "):
            intro = line

def q(s):
    return json.dumps(s, ensure_ascii=False)

lines = [f"# Generated by design/contributions.py on {datetime.date.today()}. Edit [[manual]] entries and `hide` flags by hand;",
         "# everything else is overwritten on the next run.",
         f"generated = {datetime.date.today()}",
         intro or 'intro = "Most of the studio\'s code lands in other people\'s repositories. The numbers are generated from the public pull-request record on GitHub; a few contributions on other forges are listed by hand."',
         "", "[totals]"]
lines += [f"{k} = {v}" for k, v in totals.items()]
lines.append("")
lines += manual if manual else [
    "# Contributions the GitHub search does not see. `note` is shown where the merged count would be.",
    "[[manual]]",
    'name = "cmake/cmake"', 'url = "https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5476"',
    'note = "1 merged · Kitware GitLab"', 'description = "FindProtobuf: support files with multiple extensions (2020)."', "",
    "[[manual]]",
    'name = "swaywm/sway"', 'url = "https://github.com/swaywm/sway/pull/6778"',
    'note = "1 open"', 'description = "swaybar: support gesture bindings (2022)."', "",
    "[[manual]]",
    'name = "tidklaas/hip-badge"', 'url = "https://gitlab.com/tidklaas/hip-badge/-/merge_requests"',
    'note = "2 merged · gitlab.com"', 'description = "Firmware fixes for the HiP badge (2024)."', "",
    "[[manual]]",
    'name = "memahaxx/libdrc"', 'url = "https://github.com/GaryOderNichts/libdrc"',
    'note = "7 commits · Bitbucket, 2014"', 'description = "Boot and image-resource documentation for the Wii U GamePad library."', "",
]
for r in shown:
    lines += ["[[repo]]", f"name = {q(r['name'])}", f"url = {q(r['url'])}", f"description = {q(r['description'])}",
              f"language = {q(r['language'])}", f"stars = {r['stars']}", f"prs = {r['prs']}", f"merged = {r['merged']}",
              f"first = {r['first']}", f"last = {r['last']}", f"archived = {str(r['archived']).lower()}", ""]
OUT.write_text("\n".join(lines).rstrip("\n") + "\n")
print(f"{OUT.relative_to(ROOT)}: {totals['prs']} PRs, {totals['merged']} merged, {totals['repositories']} repositories, {len(shown)} shown", file=sys.stderr)
